# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-box',
                'doc_host': 'https://Vijesh2.github.io',
                'git_url': 'https://github.com/Vijesh2/nbdev-box',
                'lib_path': 'nbdev_box'},
  'syms': {'nbdev_box.core': {'nbdev_box.core.foo': ('core.html#foo', 'nbdev_box/core.py')}}}
